server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: banking-web-services
          uri: lb://banking-web-services
          predicates:
            - Path=/account**
        - id: customer-webservices
          uri: lb://customer-webservices
          predicates:
            - Path=/api/customer/**