spring.application.name=customer-webservices
server.port=8100

#Configuration config Server
spring.config.import=optional:configserver:http://localhost:8888
#spring.cloud.config.name=customer-webservices
spring.cloud.config.profile=dev
#spring.profiles.active=dev