spring.application.name=spring-cloud-config-server
server.port=8888
#eureka client configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.config.server.git.uri=file:///Users/yashpatel/Professional/Java/Workspace/BankingApp/configuration-repo
spring.cloud.config.profile=dev
spring.profiles.active=dev
spring.cloud.config.server.git.skipSslValidation=true
#spring.cloud.config.server.git.default-label=master
spring.cloud.config.server.git.clone-on-start=true